- name: Install dependencies
  run: npm install
  working-directory: react-practice

- name: Build
  run: npm run build
  working-directory: react-practice

- name: Upload artifact
  uses: actions/upload-pages-artifact@v3
  with:
    path: ./react-practice/dist
